[package]
name = "dedup-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1"
tokio = { version = "=1", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "=0.6", features = ["full"] }

tracing = "=0.1"
tracing-subscriber = "=0.2"

[dev-dependencies]
rand = "=0.8"
